dissertation.pdf: main.tex
	latexmk -pdf -cd main.tex -jobname=output/developermanual

clean:
	rm -rf output/*
	rm -f .vscode
	rm -f *.aux
	rm -f *.fdb_latexmk
	rm -f *.fls
	rm -f *.log
	rm -f *.tkzfct.gnuplot
	rm -f *.tkzfct.table
	rm -f main-blx.bib
	rm -f main.bbl
	rm -f main.blg
	rm -f main.loa
	rm -f main.lof
	rm -f main.lot
	rm -f main.out
	rm -f main.pdf
	rm -f main.run.xml
	rm -f main.synctex.gz
	rm -f main.toc
	rm -f *.bbl
	rm -f *.blg
	rm -f *.dvi