#!/bin/bash
echo -n "start time is: " 
date
echo -n > ./Test/All.Tout
echo -n > ./Test/Long.Tout
NAME='fail'
for i in {1..168}
do
  echo -n "Running Case: " $i
  NAME="./Test"/"All.Tout"
  NAME2="./Test"/"Long.Tout"
  echo -n " || start time is:" 
  date
  echo -n $i " | " >> $NAME
  mpirun -np $i ./thor-1.0.exe ./thor_1grp.inp 2&>1 > temp
  cat temp | tail -24 | head -1  >> $NAME
  echo '============================================================' >>$NAME2
  echo '==='$i >> $NAME2
  echo '============================================================' >> $NAME2
  cat temp | tail -24 | head -6 >> $NAME2
  tail -1 ./Test/All.Tout
  echo
  echo
done

cat ./Test/All.Tout
